apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: rust-template
build:
  artifacts:
    - image: rust-template
      docker:
        dockerfile: images/api.containerfile
      sync:
        manual:
          - src: "crates/**/*.rs"
            dest: /app/source/crates
    - image: web
      docker:
        dockerfile: images/web.containerfile
      sync:
        manual:
          - src: "frontends/web/**/*.{vue,ts}"
            dest: /app
manifests:
  kustomize:
    paths:
      - kube/
portForward:
  - resourceType: deployment
    resourceName: rust-template
    port: 3000
    localPort: 3000
  - resourceType: deployment
    resourceName: web
    port: 3001
    localPort: 3001
